### ISSUE TITLE
unable to use angle brackets

### ISSUE THREAD

**Issue by bgrayburn** [ldthomas/apg-js2-examples#1]
I am unable to get angle brackets surrounding rule names in grammars to successfully generate a parser. While angle brackets are optional in ABNF, their use is sometimes necessary in cases such as the definition of path-empty in rfc3986 (sec 3.3). Here is a grammar that won't generate a parser but is valid ABNF:

```
ALPHA = %x41-5A / %x61-7A
ALPHA-EMPTY = 0<ALPHA>
```

**Comment by ldthomas** [comment]
Prose values, angle brackets, are valid ABNF but obviously can't be used to generator parser code. In your example you are simply using it as a place holder, using zero repetitions to define an empty string. APG only accepts "" (an empty literal string) as the empty string definition.

Also, since you are looking at RFC 3986 I see they talk about the "first-match-wins" algorithm. APG always uses this algorithm (also called prioritized-choice by Bryon Ford in his PEG work). They seem to have taken this into account in this RFC, but in many others they don't. You might take a look at [this discussion](http://coasttocoastresearch.com/interactiveapg/index/tutorials/6), especially exercises 3 & 4, for the kinds of problems that prioritized-choice and greedy repetitions can cause and examples of how to fix them.

**Comment by ldthomas** [comment]
Hope this helped.

**Comment by bgrayburn** [comment]
Thanks! Sorry for the delay, had to shift topics for a bit, but I'm fine calling this closed. It isn't clear to me why prose values can't be used generate parser code, but that's not a big deal for me at the moment. While my example uses it as a placeholder for an empty string, presumably it could be used to indicated rules adjoined without whitespace as well, which doesn't have such a simple replacement.

I'll take a look at the first-match-wins info and exercises you sent, thanks!

**Comment by ldthomas** [comment]
RFC 5234 defines prose-val = "<" SP and VCHAR characters ">" as a "prose description, to be used as a last resort." In other words, if you need a phrase you don't know how to describe with the other ABNF operators and elements, just describe it in the words of your spoken language. That might help a human understand what you want to do but it isn't much help to a parser generator that only understands the operators and elements.
